name: CPP DEBUG
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: [14]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++
          
      - name: Run
        run: |
         /bin/bash debug_list.sh
