name: Auto Update RAW
on:
  workflow_call:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: update
      run: |
        git config pull.rebase false
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"

        git fetch origin
        git checkout -b raw
        git merge main || true
        rm -rf .idea
        git add .
        git commit -m "Auto Update"
        git pull origin raw
        git merge origin/raw || true
        git push origin raw
