name: Auto Update RAW
on: 
  workflow_call:
  push:
    branches:
      - main
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7
    - name: update
      run: |
        git checkout -b raw
        git merge main
        git push origin raw
