name: Auto Update RAW
on:
  workflow_call:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7
      with:
        ref: raw
        fetch-depth: 0

    - name: update
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"

        git fetch origin
        git status
        echo "F1"
        git pull --force origin raw --no-commit
        echo "F1"
        git merge --strategy=ours main --no-commit
        echo "F1"
        rm -rf .idea
        git add .
        echo "F1"
        git commit -m "Auto Update"
        echo "F1"
        git push raw
